apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudguide-deployment
  labels:
    app: cloudguide
spec:
  selector:
    matchLabels:
      app: cloudguide
  template:
    metadata:
      labels:
        app: cloudguide
    spec:
      containers:
      - name: web
        image: 094033154904.dkr.ecr.eu-west-1.amazonaws.com/pythonhelloworld
        ports:
        - containerPort: 8080
